"""Compare tracked runs (course Lab 2, Task 3): reports/runs.md.

    python scripts/compare_runs.py

Two tables from the MLflow experiment: the hyperparameter runs (`make runs`, varying
max_leaf_nodes) and the seed runs (`make seeds`, one configuration, seeds 1-5). The second is
what the registration gate's margin is set from (scripts/evaluation_gate.py).
"""
from __future__ import annotations

import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import mlflow

from src import config


def main() -> int:
    cfg = config.load(strict=False)
    mlflow.set_tracking_uri(cfg.mlflow_tracking_uri)
    runs = mlflow.search_runs(experiment_names=["bike-demand"], filter_string="status = 'FINISHED'")
    if runs.empty:
        print("no finished runs in experiment bike-demand")
        return 1
    runs["minutes"] = (runs["end_time"] - runs["start_time"]).dt.total_seconds() / 60
    name = runs["tags.mlflow.runName"].fillna("")

    lines = ["# Tracked runs", "", "Experiment `bike-demand`, local MLflow store. Generated by "
             "`scripts/compare_runs.py`.", "",
             "## Hyperparameter runs — `make runs`", "",
             "| Run | max_leaf_nodes | seed | val_mae | val_mae 1 h | test_mae | minutes | commit |",
             "|---|---|---|---|---|---|---|---|"]
    leaves = runs[name.str.startswith("leaves-")].sort_values("params.max_leaf_nodes",
                                                              key=lambda s: s.astype(int))
    for _, r in leaves.iterrows():
        lines.append(f"| {r['tags.mlflow.runName']} | {r['params.max_leaf_nodes']} | "
                     f"{r['params.seed']} | {r['metrics.val_mae']:.3f} | "
                     f"{r['metrics.val_mae_h1']:.3f} | {r['metrics.test_mae']:.3f} | "
                     f"{r['minutes']:.1f} | {str(r['tags.git_commit'])[:7]} |")

    seeds = runs[name.str.startswith("seed-")]
    lines += ["", "## Seed variance — `make seeds`", "",
              "Same configuration (the defaults), seeds 1-5. The seed moves the model's own "
              "randomness only; the split is by time and does not depend on it.", "",
              "| Seed | val_mae | test_mae |", "|---|---|---|"]
    for _, r in seeds.sort_values("params.seed", key=lambda s: s.astype(int)).iterrows():
        lines.append(f"| {r['params.seed']} | {r['metrics.val_mae']:.3f} | "
                     f"{r['metrics.test_mae']:.3f} |")
    if len(seeds) >= 2:
        val = seeds["metrics.val_mae"].tolist()
        lines += ["", f"val_mae mean {statistics.mean(val):.3f}, standard deviation "
                      f"**{statistics.stdev(val):.3f}**, range {min(val):.3f}–{max(val):.3f}."]
    out = cfg.reports_dir / "runs.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
