"""Cost per 1,000 forecasts (course Lab 3 Task 5 and Lab 5 Task 5), for a batch service.

    python scripts/cost_report.py --duration-s 25 [--actual-thb 212.4]

An online endpoint costs the same idle or busy, so the course prices it at three utilisation
assumptions. A scheduled job costs nothing between runs; what plays the role of utilisation
here is VOLUME — how many forecasts share the fixed costs (registry, storage, tracking server).
So the table reports three volumes, and the marginal cost of a run separately.

Every price is a starting value to verify against the Azure Retail Prices API for eastasia, as
the course did in Lab 2 (`src/costs.py` in the course repository). Writes reports/cost.md.
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
USD_THB = 33.234                     # the course's rate, 2026-09-18 (Lab 2 README)

# Container Apps consumption plan, pay-as-you-go list price, USD.
VCPU_SECOND_USD = 0.000024
GIB_SECOND_USD = 0.000003
FREE_VCPU_SECONDS = 180_000          # monthly free grant, per subscription
FREE_GIB_SECONDS = 360_000
JOB_VCPU, JOB_GIB = 0.5, 1.0         # Dockerfile.job runs at 0.5 vCPU / 1 GiB
ROWS_PER_RUN = 24                    # one forecast per hour ahead

# Fixed monthly costs that exist whether or not a forecast is made (course Lab 2 README).
FIXED_THB_MONTH = {
    "container registry, Basic (shared with the labs)": 165.0,
    "tracking-server VM, B2ats_v2, ~4 h a day": 0.44 * 4 * 30,
    "tracking-server static IP and disk": 175.0,
    "blob storage, <1 GB": 1.0,
}


def run_cost_thb(duration_s: float) -> float:
    usd = duration_s * (JOB_VCPU * VCPU_SECOND_USD + JOB_GIB * GIB_SECOND_USD)
    return usd * USD_THB


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--duration-s", type=float, required=True,
                    help="measured job duration per run (two jobs: feeder + forecast)")
    ap.add_argument("--runs-per-day", type=int, default=24)
    ap.add_argument("--actual-thb", type=float, default=None,
                    help="from Cost Management, filtered by tag lab=capstone")
    ap.add_argument("--out", type=Path, default=ROOT / "reports" / "cost.md")
    args = ap.parse_args()

    per_run = run_cost_thb(args.duration_s)
    runs_month = args.runs_per_day * 30
    vcpu_s = runs_month * args.duration_s * JOB_VCPU
    inside_grant = vcpu_s <= FREE_VCPU_SECONDS and runs_month * args.duration_s * JOB_GIB <= FREE_GIB_SECONDS
    fixed = sum(FIXED_THB_MONTH.values())
    marginal_per_1k = per_run / ROWS_PER_RUN * 1000

    volume_rows = []
    for label, forecasts_month in (("this service: 24 runs a day", runs_month * ROWS_PER_RUN),
                                   ("x10: per-station, 10 areas", runs_month * ROWS_PER_RUN * 10),
                                   ("x100", runs_month * ROWS_PER_RUN * 100)):
        total = fixed + per_run * forecasts_month / ROWS_PER_RUN
        volume_rows.append(f"| {label} | {forecasts_month:,} | {total / forecasts_month * 1000:.2f} |")

    actual = (f"{args.actual_thb:.2f} THB" if args.actual_thb is not None
              else "_not yet: fill from Cost Management, tag lab=capstone, after a week running_")
    content = f"""# Cost per 1,000 forecasts

Generated by `make cost` (scripts/cost_report.py). Prices are list prices to verify for
eastasia; USD→THB {USD_THB}.

## 1. Estimate, made before running
Job: {JOB_VCPU} vCPU / {JOB_GIB} GiB for {args.duration_s:.0f} s a run, {args.runs_per_day} runs a day.
Marginal cost of one run: **{per_run:.5f} THB** at list price. A month is {vcpu_s:,.0f} vCPU-seconds —
{"inside" if inside_grant else "OUTSIDE"} the free grant of {FREE_VCPU_SECONDS:,}, so the job itself
bills {"nothing" if inside_grant else "the excess"} while it is the only consumer.

## 2. Actual, from billing filtered by tag
{actual}

## 3. The gap
To write once the actual is in. Expected causes, from the labs: the tracking server running
while debugging, the registry's daily rate, and runs at the demo's 5-minute tick.

## 4. Breakdown by component (monthly)
| Component | THB | Notes |
|---|---|---|
| Training (Azure ML, DS2_v2, ~10 node-minutes a run) | {7.11 / 6 * 4:.2f} | weekly retraining, 4 runs |
| Serving (the two scheduled jobs) | {0 if inside_grant else per_run * runs_month:.2f} | marginal {per_run * runs_month:.2f} at list price |
""" + "".join(f"| {k} | {v:.2f} | fixed |\n" for k, v in FIXED_THB_MONTH.items()) + f"""
## 5. Cost per 1,000 forecasts
Marginal (the job alone, list price): **{marginal_per_1k:.4f} THB** per 1,000.

Fixed costs dominate, so the honest number depends on volume — the batch analogue of the
course's utilisation assumption:

| Volume | Forecasts a month | THB per 1,000, fixed costs included |
|---|---|---|
{chr(10).join(volume_rows)}

## 6. One optimisation applied
| | Before | After |
|---|---|---|
| Hourly run on | Azure ML schedule, DS2_v2 cluster (the Lab 4 drift-job pattern) | Container Apps Job, 0.5 vCPU |
| Cost per run | ~1.2 THB (10 node-minutes from cold, course Lab 2 README) | {per_run:.5f} THB |
| Per month at 24 runs a day | ~860 THB | {per_run * runs_month:.2f} THB (inside the free grant) |

What it gave up: Azure ML's job history and lineage UI for inference runs. The forecasts and
the run log are in storage and Log Analytics instead.
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(f"wrote {args.out}: {per_run:.5f} THB a run, {marginal_per_1k:.4f} THB per 1,000 marginal")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
